version: '3.8'

services:
  webstudio:
    #build: 
      #context: ..
      #dockerfile: docker/Dockerfile
    image: rogerznts/docker-webstudio:dev
    ports:
      - "3000:5173"
      #- "3001:3000"
    command: ["sh", "-c", "pnpm run dev"]
    #command: ["sh", "-c", "pnpm migrations migrate --dev"]
    #command: ["sh", "-c", "pnpm run build && sleep infinity"]
    #command: ["/wait-for-it.sh", "db", "5432", "pnpm migrations migrate --dev && pnpm run dev"]
    #command: sleep infinity
    environment:
      - NODE_ENV=development
      - AUTH_SECRET=fb8cb81
      - DATABASE_URL=postgresql://postgres:pass@db/webstudio?pgbouncer=true
      - DIRECT_URL=postgresql://postgres:pass@db/webstudio
      - GH_CLIENT_SECRET=
      - GH_CLIENT_ID=
      - DEV_LOGIN=false
      - MAX_ASSETS_PER_PROJECT=200
      - FILE_UPLOAD_PATH=public/uploads
      - ASSET_BASE_URL=/uploads/
      - FEATURES=*
      - BUILD_ORIGIN=https://www.test
      - USER_PLAN=pro
      # MAX_UPLOAD_SIZE=10
      # S3 envs
      # S3_BUCKET=
      # S3_REGION=
      # S3_ACL="public-read"
      # S3_ENDPOINT=
      # S3_ACCESS_KEY_ID=
      # S3_SECRET_ACCESS_KEY=
      # if using r2 this your worker url
      # ASSET_CDN_URL=https://assets.webstudio.is
    volumes:
      - public_storage:/app/apps/builder/public/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webstudio_network

  db:
    image: ghcr.io/supabase/postgres:15.1.1.55
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=webstudio
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - webstudio_network

volumes:
  postgres_data:
  public_storage:


networks:
  webstudio_network:
    driver: bridge

    